services:
  - type: web
    name: vipro-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: PYTHON_VERSION
        value: 3.11
    plan: free